export default {
	"kind": "admin#directory#resources#calendars#calendarResourcesList",
	"etag": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/VSvsIEymPgXmTA_KH0RFcXmCRHQ\"",
	"items": [{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/iQmpFRjtNmRyJaldzkyo7D6NYSo\"",
			"resourceId": "-13223996238",
			"resourceName": "London - Strand (2)",
			"generatedResourceName": "London - Strand (2)",
			"resourceDescription": "London Office",
			"resourceEmail": "freshworks.com_2d3133323233393936323338@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/YlOTaleTYR3i6GR398IMUZo-e9c\"",
			"resourceId": "-16440917407",
			"resourceName": "Titanic - Blue - S10 TV",
			"generatedResourceName": "C--Block-Ground Floor-Titanic - Blue - S10 TV (10)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3136343430393137343037@resource.calendar.google.com",
			"capacity": 10,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/1xXyvT-IL9MJdoLAhNeo3rfLdE8\"",
			"resourceId": "-17923588982",
			"resourceName": "Cutty sark - Yellow - 5S",
			"generatedResourceName": "C--Block-Ground Floor-Cutty sark - Yellow - 5S (5)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3137393233353838393832@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/E9JiYlGZCYFiq3I5xS_o-LZt8rw\"",
			"resourceId": "-2162564839",
			"resourceName": "TTK road-Green-4S",
			"generatedResourceName": "C Block-First Floor-TTK road-Green-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near To Channel Manager Team",
			"resourceEmail": "freshworks.com_2d32313632353634383339@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/fxekozQ5ulssijdogsWRsR59iAA\"",
			"resourceId": "-23123939242",
			"resourceName": "Santhome beach-Yellow-5S",
			"generatedResourceName": "C Block-First Floor-Santhome beach-Yellow-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_2d3233313233393339323432@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/I223lA-R_0js5fG3EFlxxMIwOVQ\"",
			"resourceId": "-2739503826",
			"resourceName": "Sao Gabriel-Green-5S",
			"generatedResourceName": "C--Block-Ground Floor-Sao Gabriel-Green-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d32373339353033383236@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/qQ_rNVpj5kVCmbOkudPHhl0-WZ4\"",
			"resourceId": "-29712489790",
			"resourceName": "ECR Meeting Room - 3S",
			"generatedResourceName": "C Block-First Floor-ECR Meeting Room - 3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "C Block 1'st Floor - Near to HR Bay",
			"resourceEmail": "freshworks.com_2d3239373132343839373930@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/lmVCteXP2rJxF_FrIYNk7EW0ZVY\"",
			"resourceId": "-31310569370",
			"resourceName": "Rippon Building-Yellow-4S",
			"generatedResourceName": "C Block-First Floor-Rippon Building-Yellow-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_2d3331333130353639333730@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/EKqKR9Uvpvac5ip4Z3bw1iVRCcE\"",
			"resourceId": "-33376981-147",
			"resourceName": "Cybertron-Blue-4S",
			"generatedResourceName": "B Block-First Floor-Cybertron-Blue-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near to Freshservice Team",
			"resourceEmail": "freshworks.com_2d33333337363938312d313437@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/Qv6_Jryi8PwCI3PcHtp1Dn2jMCs\"",
			"resourceId": "-33795476742",
			"resourceName": "Barzan - Yellow - S3",
			"generatedResourceName": "C--Block-Ground Floor-Barzan - Yellow - S3 (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3333373935343736373432@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/HFUfVzUouhzIJy-5cur_H-Nv2KU\"",
			"resourceId": "-34196433173",
			"resourceName": "Black pearl - Blue - 4S",
			"generatedResourceName": "C--Block-Ground Floor-Black pearl - Blue - 4S (4)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3334313936343333313733@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/GTijMrMJyDYZnTY1rhajztqN6QI\"",
			"resourceId": "-36066766-633",
			"resourceName": "Tatooine-Blue-4S",
			"generatedResourceName": "B Block-First Floor-Tatooine-Blue-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d33363036363736362d363333@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/ktD_Hw3UzDhDipNMCSlKhTUIwuQ\"",
			"resourceId": "-38946244637",
			"resourceName": "Earth-Red-4S",
			"generatedResourceName": "B Block-First Floor-Earth-Red-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d3338393436323434363337@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/TEqCnSqPBb8sWsUSVDbr8ZW_yvY\"",
			"resourceId": "-4160559506",
			"resourceName": "INS Arihant - Yellow - 4S",
			"generatedResourceName": "C--Block-Ground Floor-INS Arihant - Yellow - 4S (4)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d34313630353539353036@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/ZIs8x_UfoG0gvdoF4c00vbgUULo\"",
			"resourceId": "-49027395556",
			"resourceName": "Venus-Red-5S",
			"generatedResourceName": "B Block-First Floor-Venus-Red-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d3439303237333935353536@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/JOtngIcuWxvoqGDm628udKRIoEw\"",
			"resourceId": "-4984500979",
			"resourceName": "Uranus-Red-4S",
			"generatedResourceName": "B Block-First Floor-Uranus-Red-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d34393834353030393739@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/AfTTSL7QWhHaDJ1yXPI_YDJt37E\"",
			"resourceId": "-59972102908",
			"resourceName": "Beagle - Yellow - S20 TV",
			"generatedResourceName": "C--Block-Ground Floor-Beagle - Yellow - S20 TV (20)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3539393732313032393038@resource.calendar.google.com",
			"capacity": 20,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/yD1DfbySI6_-lUT8qqz2y4Ujclc\"",
			"resourceId": "-69772421815",
			"resourceName": "Krypton-Blue-4S",
			"generatedResourceName": "B Block-First Floor-Krypton-Blue-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d3639373732343231383135@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/hEHPNHjEJvCrtmBdvQhdwU-MzTQ\"",
			"resourceId": "-73680191259",
			"resourceName": "Seraph - Green - 5S",
			"generatedResourceName": "C--Block-Ground Floor-Seraph - Green - 5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3733363830313931323539@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CONFERENCE_ROOM"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/Js_4s4oivHX3n0Wpr28cIAZ8Zn4\"",
			"resourceId": "-75334227349",
			"resourceName": "Solar sailor -Green -3S",
			"generatedResourceName": "C--Block-Ground Floor-Solar sailor -Green -3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3735333334323237333439@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/3tJR7Xwhap3_AB5pg1P1JgEdItk\"",
			"resourceId": "-76730680492",
			"resourceName": "Flying dutchman - Blue - 4S",
			"generatedResourceName": "C--Block-Ground Floor-Flying dutchman - Blue - 4S (4)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3736373330363830343932@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/IheP85SKZ48WlLE2YKpCuqBZwEo\"",
			"resourceId": "-77173218952",
			"resourceName": "Color magic -Yellow -3S",
			"generatedResourceName": "C--Block-Ground Floor-Color magic -Yellow -3S (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3737313733323138393532@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/lTMlcrwakWN1BxRrS-ac1GhVCkM\"",
			"resourceId": "-8081682578",
			"resourceName": "Kapaleeshwara Temple-Yellow-10S-TV",
			"generatedResourceName": "C Block-First Floor-Kapaleeshwara Temple-Yellow-10S-TV (10)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_2d38303831363832353738@resource.calendar.google.com",
			"capacity": 10,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/kMpvav87pXlMu7r2q5t7AGMiR64\"",
			"resourceId": "-8381449725",
			"resourceName": "Admiral - Yellow",
			"generatedResourceName": "C--Block-Ground Floor-Admiral - Yellow (3)",
			"resourceType": "conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d38333831343439373235@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN",
			"userVisibleDescription": "Ground Foor"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/aSGpTkDXbcl6HIApJd6hw0ySBRA\"",
			"resourceId": "-83994473377",
			"resourceName": "Sea shadow - Green - 3S",
			"generatedResourceName": "C--Block-Ground Floor-Sea shadow - Green - 3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3833393934343733333737@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/CwtxzXFOBlFyGmKxzFFUbNehUTs\"",
			"resourceId": "-8529804917",
			"resourceName": "Napier Bridge-Yellow-4S",
			"generatedResourceName": "C Block-First Floor-Napier Bridge-Yellow-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_2d38353239383034393137@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/-KX--dBfUqH8yDAhLsRWLWqfzHg\"",
			"resourceId": "-88291951983",
			"resourceName": "Vulcan-Blue-2S",
			"generatedResourceName": "B Block-First Floor-Vulcan-Blue-2S (2)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d3838323931393531393833@resource.calendar.google.com",
			"capacity": 2,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/JjdVNef9yjy6RkdXy3HJyv1ixSI\"",
			"resourceId": "-9024694324",
			"resourceName": "Amphitheatre-50S-1P",
			"generatedResourceName": "C Block-First Floor-Amphitheatre-50S-1P (50)",
			"resourceType": "Amphitheater",
			"resourceDescription": "Block C 1st Floor",
			"resourceEmail": "freshworks.com_2d39303234363934333234@resource.calendar.google.com",
			"capacity": 50,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/sneuUdKcmy-aNa1LucLsy0PMtos\"",
			"resourceId": "-94824945-339",
			"resourceName": "Neptune-Red-5S",
			"generatedResourceName": "B Block-First Floor-Neptune-Red-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_2d39343832343934352d333339@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/PtPSEg7MLJxLPqxTHs530220yc0\"",
			"resourceId": "-9608222370",
			"resourceName": "Neverland [Red] 4S",
			"generatedResourceName": "Neverland [Red] 4S",
			"resourceType": "Conference Room",
			"resourceDescription": "Near Big Cafetria",
			"resourceEmail": "freshworks.com_2d39363038323232333730@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/LkFCan4yOlws2xE4B5584gY05dI\"",
			"resourceId": "-96410039882",
			"resourceName": "Argo - Yellow - 3S",
			"generatedResourceName": "C--Block-Ground Floor-Argo - Yellow - 3S (3)",
			"resourceType": "conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_2d3936343130303339383832@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/11-DbYeoB6z92UUDsApV5ozvLNI\"",
			"resourceId": "12089816-200",
			"resourceName": "3M (seats 4)",
			"generatedResourceName": "3M (seats 4)",
			"resourceType": "Conference Room",
			"resourceDescription": "US-Meeting Room",
			"resourceEmail": "freshworks.com_31323038393831362d323030@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/_61ZISSv4GhBhCh3Pg_uUK2jtt0\"",
			"resourceId": "13850331127",
			"resourceName": "London - Floral (2)",
			"generatedResourceName": "London - Floral (2)",
			"resourceDescription": "London Office",
			"resourceEmail": "freshworks.com_3133383530333331313237@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/aw4F58n2L5cUwmAcpS6RqYNVvoU\"",
			"resourceId": "151624303",
			"resourceName": "Asgard-Blue-5S",
			"generatedResourceName": "B Block-First Floor-Asgard-Blue-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near to Freshservice Team",
			"resourceEmail": "freshworks.com_313531363234333033@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/GuB736JOxQdZ-tzaF8sCexTHk0Q\"",
			"resourceId": "1775983340",
			"resourceName": "Hotel California  [Blue] 4S - P",
			"generatedResourceName": "Hotel California  [Blue] 4S - P (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near Sales Team",
			"resourceEmail": "freshworks.com_31373735393833333430@resource.calendar.google.com",
			"capacity": 4,
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/9pjSm_BEu8AcouD53dbfmRciZ5Q\"",
			"resourceId": "19277957348",
			"resourceName": "Poseidon - Blue - 3S",
			"generatedResourceName": "C--Block-Ground Floor-Poseidon - Blue - 3S (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3139323737393537333438@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/XulIFmmMtVutP__NMbR7cRV4TwQ\"",
			"resourceId": "24067767966",
			"resourceName": "Mars-Red-5S",
			"generatedResourceName": "B Block-First Floor-Mars-Red-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_3234303637373637393636@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/Y_5T_3u9mr9tkMldJLBAo_PWrFE\"",
			"resourceId": "29190400138",
			"resourceName": "London - Piazza (6)",
			"generatedResourceName": "London - Piazza (6)",
			"resourceDescription": "London Office",
			"resourceEmail": "freshworks.com_3239313930343030313338@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/-UaSZ2O4E03dPNg3yNSyIF3Txwk\"",
			"resourceId": "32277250862",
			"resourceName": "Golden beach-Yellow-3S",
			"generatedResourceName": "C Block-First Floor-Golden beach-Yellow-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near To Europe Sales",
			"resourceEmail": "freshworks.com_3332323737323530383632@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/iyGmTm4dZhRPDlQ1jw-x4kB2008\"",
			"resourceId": "3505358520",
			"resourceName": "Seawise gaint-Green-3S",
			"generatedResourceName": "C--Block-Ground Floor-Seawise gaint-Green-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_33353035333538353230@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/_0kJGzHHmBSPG5Nb0c-0FpCBgDo\"",
			"resourceId": "37786885189",
			"resourceName": "Kovalam beach-Yellow -4S",
			"generatedResourceName": "C Block-First Floor-Kovalam beach-Yellow -4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near To Support Team",
			"resourceEmail": "freshworks.com_3337373836383835313839@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/aagyp1-DBSVaJe_tgL7_jtKLYzM\"",
			"resourceId": "44465251930",
			"resourceName": "Carnaby",
			"generatedResourceName": "UK Office-6th Floor-Carnaby (8)",
			"resourceEmail": "freshworks.com_3434343635323531393330@resource.calendar.google.com",
			"capacity": 8,
			"buildingId": "UK-Office",
			"floorName": "6th Floor",
			"resourceCategory": "CONFERENCE_ROOM"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/HO9e3Oera6sEs3jh6WGoQhh9P1s\"",
			"resourceId": "45210889109",
			"resourceName": "Amethyst - Yellow -5S",
			"generatedResourceName": "C--Block-Ground Floor-Amethyst - Yellow -5S (5)",
			"resourceType": "conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3435323130383839313039@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/ZtFixBxcIpGYFymhEIAdbqInIKM\"",
			"resourceId": "47287033918",
			"resourceName": "OMR Meeting Room - 3S",
			"generatedResourceName": "C Block-First Floor-OMR Meeting Room - 3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "C Block 1'st Floor - Near to HR Bay",
			"resourceEmail": "freshworks.com_3437323837303333393138@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/yZiXtQT3TS43XykG_ALUWanWHxE\"",
			"resourceId": "49820930-912",
			"resourceName": "Souq (seats 5)",
			"generatedResourceName": "Souq (seats 5)",
			"resourceType": "Conference Room",
			"resourceDescription": "US-Meeting Rooms",
			"resourceEmail": "freshworks.com_34393832303933302d393132@resource.calendar.google.com",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/c6DQbOIBXblByqde2ZqCAntbxSI\"",
			"resourceId": "50259259232",
			"resourceName": "INS S-21 - Yellow - 3S",
			"generatedResourceName": "C--Block-Ground Floor-INS S-21 - Yellow - 3S (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3530323539323539323332@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/3ZMomFeeSV43I593AMoEce7RDbw\"",
			"resourceId": "5335051295",
			"resourceName": "Valluvar Kottam-Yellow-5S",
			"generatedResourceName": "C Block-First Floor-Valluvar Kottam-Yellow-5S (5)",
			"resourceType": "Conference Room",
			"resourceEmail": "freshworks.com_35333335303531323935@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CONFERENCE_ROOM"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/AafydZlsIyZPDsL0vfQlBj69j8c\"",
			"resourceId": "53612518930",
			"resourceName": "GST Meeting Room - 3S",
			"generatedResourceName": "C Block-First Floor-GST Meeting Room - 3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "C Block First Floor - Near to HR Bay",
			"resourceEmail": "freshworks.com_3533363132353138393330@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/I7-92iQWQKJNXZk2sPrO_Pr35W8\"",
			"resourceId": "53755622911",
			"resourceName": "Fort St. George-Yellow-4S",
			"generatedResourceName": "C Block-First Floor-Fort St. George-Yellow-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_3533373535363232393131@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/umNzgjFX8ABl8LcJkSAJmmSpYfA\"",
			"resourceId": "56846138886",
			"resourceName": "Jupiter-Red-10S TV",
			"generatedResourceName": "B Block-First Floor-Jupiter-Red-10S TV (10)",
			"resourceType": "Conference Room",
			"resourceEmail": "freshworks.com_3536383436313338383836@resource.calendar.google.com",
			"capacity": 10,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CONFERENCE_ROOM",
			"userVisibleDescription": "Near to Freshteam Team"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/LnMhC_ftYDgvxhgNwIEzCeyEIcQ\"",
			"resourceId": "57180606231",
			"resourceName": "Santa Maria-Green-3S",
			"generatedResourceName": "C--Block-Ground Floor-Santa Maria-Green-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3537313830363036323331@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/qdXs8PYrV2cVR3TP5yQlbAOkKAY\"",
			"resourceId": "5952050-119",
			"resourceName": "Planet X-Blue-3S",
			"generatedResourceName": "B Block-First Floor-Planet X-Blue-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_353935323035302d313139@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/L4vqjLFPAnAX2WD7JzyEBCwPhXI\"",
			"resourceId": "6583646806",
			"resourceName": "Unicorn - Blue -3S",
			"generatedResourceName": "C--Block-Ground Floor-Unicorn - Blue -3S (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_36353833363436383036@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/4XzRNinZbJG855f-fk3RMqKs_hg\"",
			"resourceId": "67524353658",
			"resourceName": "INS Chakra - Yellow - 3S",
			"generatedResourceName": "C--Block-Ground Floor-INS Chakra - Yellow - 3S (3)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3637353234333533363538@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/NuBfnsvf9FXSFNs7AwLFFI-XOgw\"",
			"resourceId": "6926676826",
			"resourceName": "Boat club-Yellow-3S",
			"generatedResourceName": "C Block-First Floor-Boat club-Yellow-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_36393236363736383236@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/80CNdulJZWm0P7tK5bK-7gJIfYY\"",
			"resourceId": "70858135298",
			"resourceName": "Mercury-Red-5S",
			"generatedResourceName": "B Block-First Floor-Mercury-Red-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_3730383538313335323938@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/iXA2eyFaHX1VBgwcIJuP3gd5muQ\"",
			"resourceId": "71656141911",
			"resourceName": "Central Perk-86S-TV",
			"generatedResourceName": "B Block-First Floor-Central Perk-86S-TV (86)",
			"resourceType": "Big Cafeteria / Conference Room",
			"resourceDescription": "Big Cafeteria - Block B",
			"resourceEmail": "freshworks.com_3731363536313431393131@resource.calendar.google.com",
			"capacity": 86,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/3_1g2PmTSN-qnIXX_3QnzH9ktW8\"",
			"resourceId": "725731090",
			"resourceName": "Spencers Plaza-Yellow-6S",
			"generatedResourceName": "C Block-First Floor-Spencers Plaza-Yellow-6S (6)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_373235373331303930@resource.calendar.google.com",
			"capacity": 6,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/5BsfNWoHywy-j_mQ7VsVoxTBdtE\"",
			"resourceId": "74791329621",
			"resourceName": "Cathedral road-Green-4S-Ph",
			"generatedResourceName": "C Block-First Floor-Cathedral road-Green-4S-Ph (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near To Finance Bay",
			"resourceEmail": "freshworks.com_3734373931333239363231@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/cvqKmpyyk9EzXYMq1Mz6ZkUP6oI\"",
			"resourceId": "7513666751",
			"resourceName": "Batillus - Yellow - S5",
			"generatedResourceName": "C--Block-Ground Floor-Batillus - Yellow - S5 (5)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_37353133363636373531@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/-saFBASXieunhP9ZXIwAUrb70Zw\"",
			"resourceId": "7723613211",
			"resourceName": "Greams road-Green-5S",
			"generatedResourceName": "C Block-First Floor-Greams road-Green-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near To Channel Manager Team",
			"resourceEmail": "freshworks.com_37373233363133323131@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/fuouH13RF3Dl6XbWHbBgqhhX-1I\"",
			"resourceId": "78069935352",
			"resourceName": "Naboo-Blue-4S",
			"generatedResourceName": "B Block-First Floor-Naboo-Blue-4S (4)",
			"resourceType": "Conference Room",
			"resourceDescription": "Near NOC Team",
			"resourceEmail": "freshworks.com_3738303639393335333532@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/5tXsIcvSPy71tj8D-1FXIdiOzLI\"",
			"resourceId": "81429221613",
			"resourceName": "Challenger - Yellow -5S",
			"generatedResourceName": "C--Block-Ground Floor-Challenger - Yellow -5S (5)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3831343239323231363133@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/RsiBgYxo_-Dx9MZgJDig7NgHzBo\"",
			"resourceId": "8147379102",
			"resourceName": "Saturn-Red-10S TV",
			"generatedResourceName": "B Block-First Floor-Saturn-Red-10S TV (10)",
			"resourceType": "Conference Room",
			"resourceEmail": "freshworks.com_38313437333739313032@resource.calendar.google.com",
			"capacity": 10,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CONFERENCE_ROOM",
			"userVisibleDescription": "Near to Freshteam Team"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/oMv8dGkHiDgFEeAKdWI1c1UBXF0\"",
			"resourceId": "8638775614",
			"resourceName": "Theosophical Society-Yellow-6S",
			"generatedResourceName": "C Block-First Floor-Theosophical Society-Yellow-6S (6)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_38363338373735363134@resource.calendar.google.com",
			"capacity": 6,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/kzfJGnXKp41PRTuDWtyC7KMmXGM\"",
			"resourceId": "89041736246",
			"resourceName": "Rivington",
			"generatedResourceName": "UK Office-6th Floor-Rivington (6)",
			"resourceEmail": "freshworks.com_3839303431373336323436@resource.calendar.google.com",
			"capacity": 6,
			"buildingId": "UK-Office",
			"floorName": "6th Floor",
			"resourceCategory": "CONFERENCE_ROOM"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/b-dXQ2FaLqRocS2POlNWRNrM8I8\"",
			"resourceId": "91058386789",
			"resourceName": "Chennai Central-Yellow-5S",
			"generatedResourceName": "C Block-First Floor-Chennai Central-Yellow-5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block C",
			"resourceEmail": "freshworks.com_3931303538333836373839@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/R2xuBaH9OK-agpCWkL4W2ZMGUUI\"",
			"resourceId": "91722627271",
			"resourceName": "Seeadler - Green -5S",
			"generatedResourceName": "C--Block-Ground Floor-Seeadler - Green -5S (5)",
			"resourceType": "Conference Room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_3931373232363237323731@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/lp2szdIZPhfNt7vyH9qpWZ3yYa0\"",
			"resourceId": "9810514-782",
			"resourceName": "Coruscant-Blue-5S-Ph",
			"generatedResourceName": "B Block-First Floor-Coruscant-Blue-5S-Ph (5)",
			"resourceType": "Conference room",
			"resourceDescription": "Near Noc 1st Floor Block B",
			"resourceEmail": "freshworks.com_393831303531342d373832@resource.calendar.google.com",
			"capacity": 5,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/nH4MR-yQAG7H_t9mSsH22jsfxgQ\"",
			"resourceId": "99234690-297",
			"resourceName": "Andromeda-Blue-56S-TV",
			"generatedResourceName": "B Block-First Floor-Andromeda-Blue-56S-TV (56)",
			"resourceType": "Small Cafeteria / Conferece Room",
			"resourceDescription": "Small Cafeteria 1st Floor",
			"resourceEmail": "freshworks.com_39393233343639302d323937@resource.calendar.google.com",
			"capacity": 56,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/uBJs8q7fT2DZm8as7nR_5HAuaoY\"",
			"resourceId": "9986252301",
			"resourceName": "INS Viraat - Yellow - 4S",
			"generatedResourceName": "C--Block-Ground Floor-INS Viraat - Yellow - 4S (4)",
			"resourceType": "Conference room",
			"resourceDescription": "Ground Floor",
			"resourceEmail": "freshworks.com_39393836323532333031@resource.calendar.google.com",
			"capacity": 4,
			"buildingId": "C--Block",
			"floorName": "Ground Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		},
		{
			"kind": "admin#directory#resources#calendars#CalendarResource",
			"etags": "\"LW8ywR8igJCaw6tx8gAGB-fySsA/_uEx3wv9eNvwlmbFS0a-1TeWn4c\"",
			"resourceId": "99910672770",
			"resourceName": "Miller's Planet-Blue-3S",
			"generatedResourceName": "B Block-First Floor-Miller's Planet-Blue-3S (3)",
			"resourceType": "Conference Room",
			"resourceDescription": "1st Floor Block B",
			"resourceEmail": "freshworks.com_3939393130363732373730@resource.calendar.google.com",
			"capacity": 3,
			"buildingId": "B-Block",
			"floorName": "First Floor",
			"resourceCategory": "CATEGORY_UNKNOWN"
		}
	]
}
